In [2]:
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

data_path, project_path, output_path = os.getenv('DATA_PATH'), os.getenv('PROJECT_PATH'), os.getenv('OUTPUT_PATH')
os.chdir(os.path.join(project_path, 'src'))

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline

In [3]:
# # rebuild pickle file after dropping src. modules
# trajectories = Trajectories.from_user(user_id='001')
# trajectories.ugpdate_labels(user_path=os.path.join(data_path, ('001')))
# trajectories.compute_trajectories_geodataframes()
# with open(os.path.join(output_path, 'trajectories_user_001.pkl'), 'wb') as f:
#     pickle.dump(trajectories, f)

Loaded trajectory 001_0 with 961 records
Loaded trajectory 001_1 with 2128 records
Loaded trajectory 001_2 with 7075 records
Loaded trajectory 001_3 with 3676 records
Loaded trajectory 001_4 with 3236 records
Loaded trajectory 001_5 with 827 records
Loaded trajectory 001_6 with 498 records
Loaded trajectory 001_7 with 99 records
Loaded trajectory 001_8 with 647 records
Loaded trajectory 001_9 with 336 records
Loaded trajectory 001_10 with 252 records
Loaded trajectory 001_11 with 732 records
Loaded trajectory 001_12 with 1988 records
Loaded trajectory 001_13 with 1482 records
Loaded trajectory 001_14 with 3712 records
Loaded trajectory 001_15 with 1943 records
Loaded trajectory 001_16 with 537 records
Loaded trajectory 001_17 with 478 records
Loaded trajectory 001_18 with 649 records
Loaded trajectory 001_19 with 1889 records
Loaded trajectory 001_20 with 747 records
Loaded trajectory 001_21 with 5718 records
Loaded trajectory 001_22 with 254 records
Loaded trajectory 001_23 with 543 records
Loaded trajectory 001_24 with 2900 records
Loaded trajectory 001_25 with 3812 records
Loaded trajectory 001_26 with 2472 records

KeyboardInterrupt:

In [2]:
trajectories = pickle.load(open(os.path.join(output_path, 'trajectories_user_001.pkl'), 'rb'))

In [6]:
from dash import Dash, dcc, html, Input, Output, State, ctx, MATCH, ALL, callback

from layout import create_layout
import plotly.express as px

In [11]:
print('px.colors.cyclical.HSV')
px.colors.cyclical.HSV

px.colors.cyclical.HSV

['#ff0000',
 '#ffa700',
 '#afff00',
 '#08ff00',
 '#00ff9f',
 '#00b7ff',
 '#0010ff',
 '#9700ff',
 '#ff00bf',
 '#ff0000']

In [13]:
px.colors.sample_colorscale(px.colors.cyclical.HSV, [i/300 for i in range(100)])

['rgb(255, 0, 0)',
 'rgb(255, 5, 0)',
 'rgb(255, 10, 0)',
 'rgb(255, 15, 0)',
 'rgb(255, 20, 0)',
 'rgb(255, 25, 0)',
 'rgb(255, 30, 0)',
 'rgb(255, 35, 0)',
 'rgb(255, 40, 0)',
 'rgb(255, 45, 0)',
 'rgb(255, 50, 0)',
 'rgb(255, 55, 0)',
 'rgb(255, 60, 0)',
 'rgb(255, 65, 0)',
 'rgb(255, 70, 0)',
 'rgb(255, 75, 0)',
 'rgb(255, 80, 0)',
 'rgb(255, 85, 0)',
 'rgb(255, 90, 0)',
 'rgb(255, 95, 0)',
 'rgb(255, 100, 0)',
 'rgb(255, 105, 0)',
 'rgb(255, 110, 0)',
 'rgb(255, 115, 0)',
 'rgb(255, 120, 0)',
 'rgb(255, 125, 0)',
 'rgb(255, 130, 0)',
 'rgb(255, 135, 0)',
 'rgb(255, 140, 0)',
 'rgb(255, 145, 0)',
 'rgb(255, 150, 0)',
 'rgb(255, 155, 0)',
 'rgb(255, 160, 0)',
 'rgb(255, 165, 0)',
 'rgb(253, 169, 0)',
 'rgb(251, 171, 0)',
 'rgb(249, 174, 0)',
 'rgb(246, 177, 0)',
 'rgb(244, 179, 0)',
 'rgb(241, 182, 0)',
 'rgb(239, 185, 0)',
 'rgb(237, 187, 0)',
 'rgb(234, 190, 0)',
 'rgb(232, 193, 0)',
 'rgb(229, 195, 0)',
 'rgb(227, 198, 0)',
 'rgb(225, 200, 0)',
 'rgb(222, 203, 0)',
 'rgb(220, 206, 0)',
 'rgb(217, 208, 0)',
 'rgb(215, 211, 0)',
 'rgb(213, 214, 0)',
 'rgb(210, 216, 0)',
 'rgb(208, 219, 0)',
 'rgb(205, 222, 0)',
 'rgb(203, 224, 0)',
 'rgb(201, 227, 0)',
 'rgb(198, 229, 0)',
 'rgb(196, 232, 0)',
 'rgb(193, 235, 0)',
 'rgb(191, 237, 0)',
 'rgb(189, 240, 0)',
 'rgb(186, 243, 0)',
 'rgb(184, 245, 0)',
 'rgb(181, 248, 0)',
 'rgb(179, 251, 0)',
 'rgb(177, 253, 0)',
 'rgb(173, 255, 0)',
 'rgb(168, 255, 0)',
 'rgb(163, 255, 0)',
 'rgb(158, 255, 0)',
 'rgb(153, 255, 0)',
 'rgb(148, 255, 0)',
 'rgb(143, 255, 0)',
 'rgb(138, 255, 0)',
 'rgb(133, 255, 0)',
 'rgb(128, 255, 0)',
 'rgb(123, 255, 0)',
 'rgb(118, 255, 0)',
 'rgb(113, 255, 0)',
 'rgb(108, 255, 0)',
 'rgb(103, 255, 0)',
 'rgb(98, 255, 0)',
 'rgb(93, 255, 0)',
 'rgb(88, 255, 0)',
 'rgb(83, 255, 0)',
 'rgb(78, 255, 0)',
 'rgb(73, 255, 0)',
 'rgb(68, 255, 0)',
 'rgb(63, 255, 0)',
 'rgb(58, 255, 0)',
 'rgb(53, 255, 0)',
 'rgb(48, 255, 0)',
 'rgb(43, 255, 0)',
 'rgb(38, 255, 0)',
 'rgb(33, 255, 0)',
 'rgb(28, 255, 0)',
 'rgb(23, 255, 0)',
 'rgb(18, 255, 0)',
 'rgb(13, 255, 0)']

In [15]:
colors_hex = px.colors.sample_colorscale(px.colors.cyclical.HSV, [i/100 for i in range(100)])
colors_hex

['rgb(255, 0, 0)',
 'rgb(255, 15, 0)',
 'rgb(255, 30, 0)',
 'rgb(255, 45, 0)',
 'rgb(255, 60, 0)',
 'rgb(255, 75, 0)',
 'rgb(255, 90, 0)',
 'rgb(255, 105, 0)',
 'rgb(255, 120, 0)',
 'rgb(255, 135, 0)',
 'rgb(255, 150, 0)',
 'rgb(255, 165, 0)',
 'rgb(249, 174, 0)',
 'rgb(241, 182, 0)',
 'rgb(234, 190, 0)',
 'rgb(227, 198, 0)',
 'rgb(220, 206, 0)',
 'rgb(213, 214, 0)',
 'rgb(205, 222, 0)',
 'rgb(198, 229, 0)',
 'rgb(191, 237, 0)',
 'rgb(184, 245, 0)',
 'rgb(177, 253, 0)',
 'rgb(163, 255, 0)',
 'rgb(148, 255, 0)',
 'rgb(133, 255, 0)',
 'rgb(118, 255, 0)',
 'rgb(103, 255, 0)',
 'rgb(88, 255, 0)',
 'rgb(73, 255, 0)',
 'rgb(58, 255, 0)',
 'rgb(43, 255, 0)',
 'rgb(28, 255, 0)',
 'rgb(13, 255, 0)',
 'rgb(8, 255, 10)',
 'rgb(7, 255, 24)',
 'rgb(6, 255, 38)',
 'rgb(5, 255, 52)',
 'rgb(5, 255, 67)',
 'rgb(4, 255, 81)',
 'rgb(3, 255, 95)',
 'rgb(2, 255, 110)',
 'rgb(2, 255, 124)',
 'rgb(1, 255, 138)',
 'rgb(0, 255, 153)',
 'rgb(0, 251, 164)',
 'rgb(0, 245, 172)',
 'rgb(0, 238, 181)',
 'rgb(0, 232, 190)',
 'rgb(0, 225, 198)',
 'rgb(0, 219, 207)',
 'rgb(0, 213, 216)',
 'rgb(0, 206, 224)',
 'rgb(0, 200, 233)',
 'rgb(0, 193, 242)',
 'rgb(0, 187, 250)',
 'rgb(0, 176, 255)',
 'rgb(0, 161, 255)',
 'rgb(0, 146, 255)',
 'rgb(0, 131, 255)',
 'rgb(0, 116, 255)',
 'rgb(0, 101, 255)',
 'rgb(0, 86, 255)',
 'rgb(0, 71, 255)',
 'rgb(0, 56, 255)',
 'rgb(0, 41, 255)',
 'rgb(0, 26, 255)',
 'rgb(5, 16, 255)',
 'rgb(18, 14, 255)',
 'rgb(32, 13, 255)',
 'rgb(45, 11, 255)',
 'rgb(59, 10, 255)',
 'rgb(72, 8, 255)',
 'rgb(86, 7, 255)',
 'rgb(100, 5, 255)',
 'rgb(113, 4, 255)',
 'rgb(127, 3, 255)',
 'rgb(140, 1, 255)',
 'rgb(153, 0, 254)',
 'rgb(162, 0, 248)',
 'rgb(172, 0, 242)',
 'rgb(181, 0, 236)',
 'rgb(191, 0, 231)',
 'rgb(200, 0, 225)',
 'rgb(209, 0, 219)',
 'rgb(219, 0, 213)',
 'rgb(228, 0, 208)',
 'rgb(237, 0, 202)',
 'rgb(247, 0, 196)',
 'rgb(255, 0, 189)',
 'rgb(255, 0, 172)',
 'rgb(255, 0, 155)',
 'rgb(255, 0, 138)',
 'rgb(255, 0, 120)',
 'rgb(255, 0, 103)',
 'rgb(255, 0, 86)',
 'rgb(255, 0, 69)',
 'rgb(255, 0, 52)',
 'rgb(255, 0, 34)',
 'rgb(255, 0, 17)']

In [9]:
trajectories.trajectories[0].gdf.iloc[0].datetime

Timestamp('2008-10-23 05:53:05')

In [8]:
# convert timestamp np.float64(1224741185.0) to datetime
pd.to_datetime(trajectories.trajectories[0].gdf.iloc[0].timestamp, unit='s')

Timestamp('2008-10-23 05:53:05')

In [3]:
trajectories = pickle.load(open(os.path.join(output_path, 'trajectories_user_001.pkl'), 'rb'))

In [32]:
trajectories.gdf

AttributeError: 'NoneType' object has no attribute 'gdf'

In [4]:
len(trajectories.gdf)

108607

In [23]:
import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

trajectories = pickle.load(open(os.path.join(output_path, 'trajectories_user_001.pkl'), 'rb'))

In [34]:
relayout_data = {'xaxis.range[0]': '2008-10-23 09:56:58.7801', 'xaxis.range[1]': '2008-10-23 10:47:02.892'}
start_datetime = pd.to_datetime(relayout_data['xaxis.range[0]'])
end_datetime = pd.to_datetime(relayout_data['xaxis.range[1]'])
range_datetime = [start_datetime, end_datetime]
range_datetime

[Timestamp('2008-10-23 09:56:58.780100'),
 Timestamp('2008-10-23 10:47:02.892000')]

In [35]:
t0 = trajectories.trajectories[0]
t0.gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
0,001,001_0,39.984094,116.319236,492,2008-10-23 05:53:05,1.224741e+09,None,0.0,0.000000,0.000000
1,001,001_0,39.984198,116.319322,492,2008-10-23 05:53:06,1.224741e+09,None,1.0,13.685897,13.685897
2,001,001_0,39.984224,116.319402,492,2008-10-23 05:53:11,1.224741e+09,None,5.0,7.417894,1.483579
3,001,001_0,39.984211,116.319389,492,2008-10-23 05:53:16,1.224741e+09,None,5.0,1.821118,0.364224
4,001,001_0,39.984217,116.319422,491,2008-10-23 05:53:21,1.224741e+09,None,5.0,2.896307,0.579261
...,...,...,...,...,...,...,...,...,...,...,...
956,001,001_0,40.013804,116.306532,90,2008-10-23 12:04:13,1.224763e+09,None,5.0,0.000000,0.000000
957,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:18,1.224763e+09,None,5.0,0.111035,0.022207
958,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:23,1.224763e+09,None,5.0,0.000000,0.000000
959,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:26,1.224763e+09,None,3.0,0.000000,0.000000
960,001,001_0,40.013803,116.306531,90,2008-10-23 12:04:28,1.224763e+09,None,2.0,0.085377,0.042688

In [38]:
r = [record for record in t0.records]
len(r)

241

In [39]:
pd.DataFrame(r)

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label
0,001,001_0,39.970511,116.341455,492,2008-10-23 10:32:53,1.224758e+09,None
1,001,001_0,39.977648,116.326925,277,2008-10-23 10:33:00,1.224758e+09,None
2,001,001_0,39.977586,116.326918,296,2008-10-23 10:33:05,1.224758e+09,None
3,001,001_0,39.977596,116.326894,299,2008-10-23 10:33:10,1.224758e+09,None
4,001,001_0,39.977661,116.326947,280,2008-10-23 10:33:14,1.224758e+09,None
...,...,...,...,...,...,...,...,...
236,001,001_0,39.999765,116.326273,115,2008-10-23 10:46:50,1.224759e+09,None
237,001,001_0,39.999828,116.326187,119,2008-10-23 10:46:53,1.224759e+09,None
238,001,001_0,39.999840,116.326064,123,2008-10-23 10:46:56,1.224759e+09,None
239,001,001_0,39.999848,116.325937,126,2008-10-23 10:46:59,1.224759e+09,None
240,001,001_0,39.999850,116.325819,130,2008-10-23 10:47:02,1.224759e+09,None

## Le gdf n'est pas mis à jour lors du filtrage !

il faudrait peut-être étendre la classe Record, de plus il faut segmenter au sein des trajectory car 1 trajectory = points d'une journée.

In [41]:
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

data_path, project_path, output_path = os.getenv('DATA_PATH'), os.getenv('PROJECT_PATH'), os.getenv('OUTPUT_PATH')
os.chdir(os.path.join(project_path, 'src'))

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline

In [42]:
t = pickle.load(open(os.path.join(output_path, 'trajectories_001.pkl'), 'rb'))

In [43]:
t.gdf.shape[0]

108607

In [44]:
relayout_data = {'xaxis.range[0]': '2008-10-23 09:56:58.7801', 'xaxis.range[1]': '2008-10-23 10:47:02.892'}
start_datetime = pd.to_datetime(relayout_data['xaxis.range[0]'].split('.')[0])
end_datetime = pd.to_datetime(relayout_data['xaxis.range[1]'].split('.')[0])
range_datetime = [start_datetime, end_datetime]
range_datetime

[Timestamp('2008-10-23 09:56:58'), Timestamp('2008-10-23 10:47:02')]

In [45]:
# from datetime import datetime
# from typing import Tuple
# import geopandas as gpd

# def filter_by_datetimerange(
#         trajectory: Trajectory,
#         datetime_range: Tuple[datetime, datetime]
#     ) -> 'Trajectory':
#         """
#         Filter the trajectory records by a specific time range
#         """
#         records = [record for record in trajectory.records if datetime_range[0] <= record.datetime <= datetime_range[1]]
#         trajectory.records = records
#         trajectory.gdf = gpd.GeoDataFrame(records)
#         return trajectory

In [46]:
tj = t.trajectories[0]
print(len(tj.records))

961

In [47]:
tj.filter_by_datetimerange(range_datetime)
tj.gdf.shape[0]

241

In [48]:
t = Trajectories.from_user(user_id='001')

Loaded trajectory 001_0 with 961 records
Loaded trajectory 001_1 with 2128 records
Loaded trajectory 001_2 with 7075 records
Loaded trajectory 001_3 with 3676 records
Loaded trajectory 001_4 with 3236 records
Loaded trajectory 001_5 with 827 records
Loaded trajectory 001_6 with 498 records
Loaded trajectory 001_7 with 99 records
Loaded trajectory 001_8 with 647 records
Loaded trajectory 001_9 with 336 records
Loaded trajectory 001_10 with 252 records
Loaded trajectory 001_11 with 732 records
Loaded trajectory 001_12 with 1988 records
Loaded trajectory 001_13 with 1482 records
Loaded trajectory 001_14 with 3712 records
Loaded trajectory 001_15 with 1943 records
Loaded trajectory 001_16 with 537 records
Loaded trajectory 001_17 with 478 records
Loaded trajectory 001_18 with 649 records
Loaded trajectory 001_19 with 1889 records
Loaded trajectory 001_20 with 747 records
Loaded trajectory 001_21 with 5718 records
Loaded trajectory 001_22 with 254 records
Loaded trajectory 001_23 with 543 records
Loaded trajectory 001_24 with 2900 records
Loaded trajectory 001_25 with 3812 records
Loaded trajectory 001_26 with 2472 records
Loaded trajectory 001_27 with 789 records
Loaded trajectory 001_28 with 323 records
Loaded trajectory 001_29 with 1612 records
Loaded trajectory 001_30 with 832 records
Loaded trajectory 001_31 with 495 records
Loaded trajectory 001_32 with 656 records
Loaded trajectory 001_33 with 981 records
Loaded trajectory 001_34 with 5663 records
Loaded trajectory 001_35 with 2789 records
Loaded trajectory 001_36 with 1000 records
Loaded trajectory 001_37 with 3028 records
Loaded trajectory 001_38 with 694 records
Loaded trajectory 001_39 with 145 records
Loaded trajectory 001_40 with 821 records
Loaded trajectory 001_41 with 859 records
Loaded trajectory 001_42 with 1779 records
Loaded trajectory 001_43 with 697 records
Loaded trajectory 001_44 with 863 records
Loaded trajectory 001_45 with 721 records
Loaded trajectory 001_46 with 491 records
Loaded trajectory 001_47 with 482 records
Loaded trajectory 001_48 with 516 records
Loaded trajectory 001_49 with 538 records
Loaded trajectory 001_50 with 934 records
Loaded trajectory 001_51 with 566 records
Loaded trajectory 001_52 with 859 records
Loaded trajectory 001_53 with 495 records
Loaded trajectory 001_54 with 2868 records
Loaded trajectory 001_55 with 59 records
Loaded trajectory 001_56 with 33 records
Loaded trajectory 001_57 with 117 records
Loaded trajectory 001_58 with 2564 records
Loaded trajectory 001_59 with 534 records
Loaded trajectory 001_60 with 603 records
Loaded trajectory 001_61 with 6959 records
Loaded trajectory 001_62 with 835 records
Loaded trajectory 001_63 with 1456 records
Loaded trajectory 001_64 with 888 records
Loaded trajectory 001_65 with 919 records
Loaded trajectory 001_66 with 1842 records
Loaded trajectory 001_67 with 691 records
Loaded trajectory 001_68 with 7584 records
Loaded trajectory 001_69 with 897 records
Loaded trajectory 001_70 with 539 records

In [49]:
t.gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
0,001,001_0,39.984094,116.319236,492,2008-10-23 05:53:05,1.224741e+09,None,None,None,None
1,001,001_0,39.984198,116.319322,492,2008-10-23 05:53:06,1.224741e+09,None,None,None,None
2,001,001_0,39.984224,116.319402,492,2008-10-23 05:53:11,1.224741e+09,None,None,None,None
3,001,001_0,39.984211,116.319389,492,2008-10-23 05:53:16,1.224741e+09,None,None,None,None
4,001,001_0,39.984217,116.319422,491,2008-10-23 05:53:21,1.224741e+09,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
534,001,001_70,39.977969,116.326651,311,2008-12-15 00:30:58,1.229301e+09,None,None,None,None
535,001,001_70,39.977946,116.326653,310,2008-12-15 00:31:03,1.229301e+09,None,None,None,None
536,001,001_70,39.977897,116.326624,310,2008-12-15 00:31:08,1.229301e+09,None,None,None,None
537,001,001_70,39.977882,116.326626,310,2008-12-15 00:31:13,1.229301e+09,None,None,None,None
538,001,001_70,39.977879,116.326628,310,2008-12-15 00:31:18,1.229301e+09,None,None,None,None

In [130]:
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

data_path, project_path, output_path = os.getenv('DATA_PATH'), os.getenv('PROJECT_PATH'), os.getenv('OUTPUT_PATH')
os.chdir(os.path.join(project_path, 'src'))

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline

In [131]:
t = pickle.load(open(os.path.join(output_path, 'trajectories_001.pkl'), 'rb'))
len(t.trajectories)

71

In [132]:
relayoutData = {'xaxis.range[0]': '2008-10-23 09:30:41.6213', 'xaxis.range[1]': '2008-10-23 10:45:10.2378'}
start_datetime = pd.to_datetime(relayoutData['xaxis.range[0]'].split('.')[0])
end_datetime = pd.to_datetime(relayoutData['xaxis.range[1]'].split('.')[0])
datetime_range = [start_datetime, end_datetime]
datetime_range

[Timestamp('2008-10-23 09:30:41'), Timestamp('2008-10-23 10:45:10')]

In [133]:
tt = t.trajectories[0]
len(tt.records), len(tt.gdf)

(961, 961)

In [134]:
tt = tt.filter_by_datetimerange(datetime_range)
len(tt.records), len(tt.gdf)

(204, 204)

In [125]:
relayoutData = {'xaxis.range[0]': '2000-10-23 09:30:41.6213', 'xaxis.range[1]': '2001-10-23 10:45:10.2378'}
start_datetime = pd.to_datetime(relayoutData['xaxis.range[0]'].split('.')[0])
end_datetime = pd.to_datetime(relayoutData['xaxis.range[1]'].split('.')[0])
datetime_range = [start_datetime, end_datetime]
datetime_range

[Timestamp('2000-10-23 09:30:41'), Timestamp('2001-10-23 10:45:10')]

In [126]:
t.trajectories[0].filter_by_datetimerange(datetime_range)

Trajectory(trajectory_id='001_0', user_id='001', records=[], gdf=Empty GeoDataFrame
Columns: [geometry]
Index: [])

In [127]:
sum([len(trajectory.records) for trajectory in t.trajectories]), t.gdf.shape[0]

(108607, 108607)

In [128]:
sum([len(trajectory.records) for trajectory in t.trajectories]), t.gdf.shape[0]

(108607, 108607)

In [143]:
filtered_trajectories = Trajectories(
    [
        trajectory.filter_by_datetimerange(datetime_range)
        for trajectory in t.trajectories
        if trajectory.filter_by_datetimerange(datetime_range).gdf.shape[0] > 0
    ]
)

In [144]:
len(filtered_trajectories.trajectories), filtered_trajectories.gdf.shape[0]

(1, 204)

In [168]:

import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

data_path, project_path, output_path = os.getenv('DATA_PATH'), os.getenv('PROJECT_PATH'), os.getenv('OUTPUT_PATH')
os.chdir(os.path.join(project_path, 'src'))

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline


t: Trajectories = pickle.load(open(os.path.join(output_path, 'trajectories_001.pkl'), 'rb'))
len(t.trajectories)

71

In [169]:
relayoutData = {'xaxis.range[0]': '2008-10-23 09:30:41.6213', 'xaxis.range[1]': '2008-10-23 10:45:10.2378'}
start_datetime = pd.to_datetime(relayoutData['xaxis.range[0]'].split('.')[0])
end_datetime = pd.to_datetime(relayoutData['xaxis.range[1]'].split('.')[0])
datetime_range = [start_datetime, end_datetime]
datetime_range

[Timestamp('2008-10-23 09:30:41'), Timestamp('2008-10-23 10:45:10')]

In [155]:
t.filter_trajectories(datetime_range)

Trajectories(trajectories=[Trajectory(trajectory_id='001_0', user_id='001', records=[Record(user_id='001', trajectory_id='001_0', latitude=39.970511, longitude=116.341455, altitude=492, datetime=Timestamp('2008-10-23 10:32:53'), timestamp=1224757973.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977648, longitude=116.326925, altitude=277, datetime=Timestamp('2008-10-23 10:33:00'), timestamp=1224757980.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977586, longitude=116.326918, altitude=296, datetime=Timestamp('2008-10-23 10:33:05'), timestamp=1224757985.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977596, longitude=116.326894, altitude=299, datetime=Timestamp('2008-10-23 10:33:10'), timestamp=1224757990.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977661, longitude=116.326947, altitude=280, datetime=Timestamp('2008-10-23 10:33:14'), timestamp=1224757994.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977647, longitude=116.326951, altitude=277, datetime=Timestamp('2008-10-23 10:33:19'), timestamp=1224757999.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977653, longitude=116.326857, altitude=261, datetime=Timestamp('2008-10-23 10:33:24'), timestamp=1224758004.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977688, longitude=116.326887, altitude=259, datetime=Timestamp('2008-10-23 10:33:29'), timestamp=1224758009.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977748, longitude=116.326978, altitude=241, datetime=Timestamp('2008-10-23 10:33:33'), timestamp=1224758013.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.97781, longitude=116.326995, altitude=240, datetime=Timestamp('2008-10-23 10:33:38'), timestamp=1224758018.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977909, longitude=116.327128, altitude=237, datetime=Timestamp('2008-10-23 10:33:43'), timestamp=1224758023.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977979, longitude=116.327218, altitude=239, datetime=Timestamp('2008-10-23 10:33:47'), timestamp=1224758027.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978093, longitude=116.327214, altitude=241, datetime=Timestamp('2008-10-23 10:33:50'), timestamp=1224758030.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978198, longitude=116.32719, altitude=241, datetime=Timestamp('2008-10-23 10:33:53'), timestamp=1224758033.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978254, longitude=116.327165, altitude=238, datetime=Timestamp('2008-10-23 10:33:58'), timestamp=1224758038.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978273, longitude=116.327255, altitude=230, datetime=Timestamp('2008-10-23 10:34:03'), timestamp=1224758043.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978385, longitude=116.327279, altitude=227, datetime=Timestamp('2008-10-23 10:34:04'), timestamp=1224758044.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978487, longitude=116.327293, altitude=223, datetime=Timestamp('2008-10-23 10:34:06'), timestamp=1224758046.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978611, longitude=116.327292, altitude=217, datetime=Timestamp('2008-10-23 10:34:08'), timestamp=1224758048.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.97872, longitude=116.327293, altitude=204, datetime=Timestamp('2008-10-23 10:34:11'), timestamp=1224758051.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978803, longitude=116.327292, altitude=188, datetime=Timestamp('2008-10-23 10:34:16'), timestamp=1224758056.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978883, longitude=116.327259, altitude=174, datetime=Timestamp('2008-10-23 10:34:21'), timestamp=1224758061.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978971, longitude=116.327242, altitude=163, datetime=Timestamp('2008-10-23 10:34:24'), timestamp=1224758064.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979016, longitude=116.327244, altitude=155, datetime=Timestamp('2008-10-23 10:34:29'), timestamp=1224758069.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979017, longitude=116.327211, altitude=154, datetime=Timestamp('2008-10-23 10:34:34'), timestamp=1224758074.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979013, longitude=116.327154, altitude=150, datetime=Timestamp('2008-10-23 10:34:39'), timestamp=1224758079.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979088, longitude=116.327131, altitude=148, datetime=Timestamp('2008-10-23 10:34:44'), timestamp=1224758084.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979104, longitude=116.327143, altitude=143, datetime=Timestamp('2008-10-23 10:34:49'), timestamp=1224758089.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979195, longitude=116.327168, altitude=137, datetime=Timestamp('2008-10-23 10:34:52'), timestamp=1224758092.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979293, longitude=116.327209, altitude=134, datetime=Timestamp('2008-10-23 10:34:55'), timestamp=1224758095.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979394, longitude=116.327208, altitude=132, datetime=Timestamp('2008-10-23 10:34:58'), timestamp=1224758098.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979497, longitude=116.327198, altitude=131, datetime=Timestamp('2008-10-23 10:35:00'), timestamp=1224758100.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979629, longitude=116.327197, altitude=131, datetime=Timestamp('2008-10-23 10:35:02'), timestamp=1224758102.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979719, longitude=116.327182, altitude=128, datetime=Timestamp('2008-10-23 10:35:05'), timestamp=1224758105.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979831, longitude=116.327185, altitude=132, datetime=Timestamp('2008-10-23 10:35:07'), timestamp=1224758107.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979919, longitude=116.327151, altitude=124, datetime=Timestamp('2008-10-23 10:35:12'), timestamp=1224758112.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979973, longitude=116.327109, altitude=109, datetime=Timestamp('2008-10-23 10:35:17'), timestamp=1224758117.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980092, longitude=116.327084, altitude=96, datetime=Timestamp('2008-10-23 10:35:21'), timestamp=1224758121.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980126, longitude=116.327037, altitude=83, datetime=Timestamp('2008-10-23 10:35:26'), timestamp=1224758126.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980188, longitude=116.326994, altitude=69, datetime=Timestamp('2008-10-23 10:35:31'), timestamp=1224758131.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98028, longitude=116.326988, altitude=66, datetime=Timestamp('2008-10-23 10:35:36'), timestamp=1224758136.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980404, longitude=116.326978, altitude=63, datetime=Timestamp('2008-10-23 10:35:39'), timestamp=1224758139.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980522, longitude=116.326976, altitude=58, datetime=Timestamp('2008-10-23 10:35:43'), timestamp=1224758143.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980658, longitude=116.326933, altitude=49, datetime=Timestamp('2008-10-23 10:35:45'), timestamp=1224758145.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980765, longitude=116.326905, altitude=45, datetime=Timestamp('2008-10-23 10:35:48'), timestamp=1224758148.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98087, longitude=116.326873, altitude=40, datetime=Timestamp('2008-10-23 10:35:51'), timestamp=1224758151.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980956, longitude=116.32682, altitude=34, datetime=Timestamp('2008-10-23 10:35:55'), timestamp=1224758155.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981364, longitude=116.326798, altitude=16, datetime=Timestamp('2008-10-23 10:36:01'), timestamp=1224758161.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981473, longitude=116.326765, altitude=11, datetime=Timestamp('2008-10-23 10:36:03'), timestamp=1224758163.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981748, longitude=116.326759, altitude=19, datetime=Timestamp('2008-10-23 10:36:06'), timestamp=1224758166.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981959, longitude=116.326767, altitude=26, datetime=Timestamp('2008-10-23 10:36:07'), timestamp=1224758167.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982049, longitude=116.326757, altitude=26, datetime=Timestamp('2008-10-23 10:36:08'), timestamp=1224758168.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982175, longitude=116.326752, altitude=29, datetime=Timestamp('2008-10-23 10:36:09'), timestamp=1224758169.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98228, longitude=116.326754, altitude=31, datetime=Timestamp('2008-10-23 10:36:10'), timestamp=1224758170.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982387, longitude=116.326752, altitude=31, datetime=Timestamp('2008-10-23 10:36:12'), timestamp=1224758172.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982508, longitude=116.326766, altitude=31, datetime=Timestamp('2008-10-23 10:36:15'), timestamp=1224758175.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982601, longitude=116.32673, altitude=29, datetime=Timestamp('2008-10-23 10:36:20'), timestamp=1224758180.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982675, longitude=116.326684, altitude=22, datetime=Timestamp('2008-10-23 10:36:25'), timestamp=1224758185.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982808, longitude=116.32671, altitude=16, datetime=Timestamp('2008-10-23 10:36:29'), timestamp=1224758189.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982922, longitude=116.326697, altitude=13, datetime=Timestamp('2008-10-23 10:36:32'), timestamp=1224758192.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983115, longitude=116.326693, altitude=8, datetime=Timestamp('2008-10-23 10:36:35'), timestamp=1224758195.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983215, longitude=116.326708, altitude=10, datetime=Timestamp('2008-10-23 10:36:38'), timestamp=1224758198.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98336, longitude=116.326707, altitude=17, datetime=Timestamp('2008-10-23 10:36:42'), timestamp=1224758202.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983434, longitude=116.326665, altitude=3, datetime=Timestamp('2008-10-23 10:36:47'), timestamp=1224758207.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983559, longitude=116.326665, altitude=0, datetime=Timestamp('2008-10-23 10:36:50'), timestamp=1224758210.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983719, longitude=116.326661, altitude=-1, datetime=Timestamp('2008-10-23 10:36:52'), timestamp=1224758212.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983839, longitude=116.326694, altitude=11, datetime=Timestamp('2008-10-23 10:36:54'), timestamp=1224758214.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983933, longitude=116.326715, altitude=18, datetime=Timestamp('2008-10-23 10:36:56'), timestamp=1224758216.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984062, longitude=116.326728, altitude=29, datetime=Timestamp('2008-10-23 10:37:00'), timestamp=1224758220.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984142, longitude=116.326753, altitude=35, datetime=Timestamp('2008-10-23 10:37:05'), timestamp=1224758225.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984164, longitude=116.326724, altitude=31, datetime=Timestamp('2008-10-23 10:37:10'), timestamp=1224758230.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984262, longitude=116.326723, altitude=28, datetime=Timestamp('2008-10-23 10:37:15'), timestamp=1224758235.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984354, longitude=116.326715, altitude=27, datetime=Timestamp('2008-10-23 10:37:18'), timestamp=1224758238.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984457, longitude=116.326711, altitude=29, datetime=Timestamp('2008-10-23 10:37:21'), timestamp=1224758241.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984559, longitude=116.326696, altitude=27, datetime=Timestamp('2008-10-23 10:37:26'), timestamp=1224758246.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984669, longitude=116.326711, altitude=29, datetime=Timestamp('2008-10-23 10:37:30'), timestamp=1224758250.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984783, longitude=116.326683, altitude=25, datetime=Timestamp('2008-10-23 10:37:35'), timestamp=1224758255.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984889, longitude=116.326672, altitude=18, datetime=Timestamp('2008-10-23 10:37:39'), timestamp=1224758259.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985019, longitude=116.326677, altitude=20, datetime=Timestamp('2008-10-23 10:37:42'), timestamp=1224758262.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985106, longitude=116.326694, altitude=28, datetime=Timestamp('2008-10-23 10:37:43'), timestamp=1224758263.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985197, longitude=116.326686, altitude=31, datetime=Timestamp('2008-10-23 10:37:45'), timestamp=1224758265.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985304, longitude=116.326664, altitude=29, datetime=Timestamp('2008-10-23 10:37:48'), timestamp=1224758268.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985454, longitude=116.32661, altitude=31, datetime=Timestamp('2008-10-23 10:37:52'), timestamp=1224758272.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985546, longitude=116.326565, altitude=28, datetime=Timestamp('2008-10-23 10:37:57'), timestamp=1224758277.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985645, longitude=116.326589, altitude=29, datetime=Timestamp('2008-10-23 10:38:00'), timestamp=1224758280.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985752, longitude=116.326618, altitude=28, datetime=Timestamp('2008-10-23 10:38:03'), timestamp=1224758283.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98585, longitude=116.326633, altitude=33, datetime=Timestamp('2008-10-23 10:38:06'), timestamp=1224758286.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985948, longitude=116.326605, altitude=36, datetime=Timestamp('2008-10-23 10:38:10'), timestamp=1224758290.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.986049, longitude=116.326554, altitude=38, datetime=Timestamp('2008-10-23 10:38:14'), timestamp=1224758294.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', l

In [156]:
t.filter_trajectories(datetime_range).gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed,geometry
0,001,001_0,39.970511,116.341455,492,2008-10-23 10:32:53,1.224758e+09,None,None,None,None,POINT (116.34146 39.97051)
1,001,001_0,39.977648,116.326925,277,2008-10-23 10:33:00,1.224758e+09,None,None,None,None,POINT (116.32692 39.97765)
2,001,001_0,39.977586,116.326918,296,2008-10-23 10:33:05,1.224758e+09,None,None,None,None,POINT (116.32692 39.97759)
3,001,001_0,39.977596,116.326894,299,2008-10-23 10:33:10,1.224758e+09,None,None,None,None,POINT (116.32689 39.9776)
4,001,001_0,39.977661,116.326947,280,2008-10-23 10:33:14,1.224758e+09,None,None,None,None,POINT (116.32695 39.97766)
...,...,...,...,...,...,...,...,...,...,...,...,...
199,001,001_0,39.995749,116.326488,176,2008-10-23 10:44:53,1.224759e+09,None,None,None,None,POINT (116.32649 39.99575)
200,001,001_0,39.995853,116.326562,161,2008-10-23 10:44:55,1.224759e+09,None,None,None,None,POINT (116.32656 39.99585)
201,001,001_0,39.995894,116.326665,145,2008-10-23 10:44:59,1.224759e+09,None,None,None,None,POINT (116.32666 39.99589)
202,001,001_0,39.995959,116.326688,139,2008-10-23 10:45:04,1.224759e+09,None,None,None,None,POINT (116.32669 39.99596)
203,001,001_0,39.996067,116.326669,134,2008-10-23 10:45:09,1.224759e+09,None,None,None,None,POINT (116.32667 39.99607)

In [157]:
t.trajectories[0].records[0]

Record(user_id='001', trajectory_id='001_0', latitude=39.984094, longitude=116.319236, altitude=492, datetime=Timestamp('2008-10-23 05:53:05'), timestamp=1224741185.0, label=None, time_diff=None, distance=None, speed=None)

In [172]:
t.trajectories[0].records[1]

Record(user_id='001', trajectory_id='001_0', latitude=39.984198, longitude=116.319322, altitude=492, datetime=Timestamp('2008-10-23 05:53:06'), timestamp=1224741186.0, label=None, time_diff=None, distance=None, speed=None)

In [165]:
t.trajectories[0].filter_by_datetimerange(datetime_range)

Trajectory(trajectory_id='001_0', user_id='001', records=[Record(user_id='001', trajectory_id='001_0', latitude=39.970511, longitude=116.341455, altitude=492, datetime=Timestamp('2008-10-23 10:32:53'), timestamp=1224757973.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977648, longitude=116.326925, altitude=277, datetime=Timestamp('2008-10-23 10:33:00'), timestamp=1224757980.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977586, longitude=116.326918, altitude=296, datetime=Timestamp('2008-10-23 10:33:05'), timestamp=1224757985.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977596, longitude=116.326894, altitude=299, datetime=Timestamp('2008-10-23 10:33:10'), timestamp=1224757990.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977661, longitude=116.326947, altitude=280, datetime=Timestamp('2008-10-23 10:33:14'), timestamp=1224757994.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977647, longitude=116.326951, altitude=277, datetime=Timestamp('2008-10-23 10:33:19'), timestamp=1224757999.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977653, longitude=116.326857, altitude=261, datetime=Timestamp('2008-10-23 10:33:24'), timestamp=1224758004.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977688, longitude=116.326887, altitude=259, datetime=Timestamp('2008-10-23 10:33:29'), timestamp=1224758009.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977748, longitude=116.326978, altitude=241, datetime=Timestamp('2008-10-23 10:33:33'), timestamp=1224758013.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.97781, longitude=116.326995, altitude=240, datetime=Timestamp('2008-10-23 10:33:38'), timestamp=1224758018.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977909, longitude=116.327128, altitude=237, datetime=Timestamp('2008-10-23 10:33:43'), timestamp=1224758023.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.977979, longitude=116.327218, altitude=239, datetime=Timestamp('2008-10-23 10:33:47'), timestamp=1224758027.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978093, longitude=116.327214, altitude=241, datetime=Timestamp('2008-10-23 10:33:50'), timestamp=1224758030.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978198, longitude=116.32719, altitude=241, datetime=Timestamp('2008-10-23 10:33:53'), timestamp=1224758033.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978254, longitude=116.327165, altitude=238, datetime=Timestamp('2008-10-23 10:33:58'), timestamp=1224758038.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978273, longitude=116.327255, altitude=230, datetime=Timestamp('2008-10-23 10:34:03'), timestamp=1224758043.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978385, longitude=116.327279, altitude=227, datetime=Timestamp('2008-10-23 10:34:04'), timestamp=1224758044.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978487, longitude=116.327293, altitude=223, datetime=Timestamp('2008-10-23 10:34:06'), timestamp=1224758046.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978611, longitude=116.327292, altitude=217, datetime=Timestamp('2008-10-23 10:34:08'), timestamp=1224758048.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.97872, longitude=116.327293, altitude=204, datetime=Timestamp('2008-10-23 10:34:11'), timestamp=1224758051.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978803, longitude=116.327292, altitude=188, datetime=Timestamp('2008-10-23 10:34:16'), timestamp=1224758056.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978883, longitude=116.327259, altitude=174, datetime=Timestamp('2008-10-23 10:34:21'), timestamp=1224758061.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.978971, longitude=116.327242, altitude=163, datetime=Timestamp('2008-10-23 10:34:24'), timestamp=1224758064.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979016, longitude=116.327244, altitude=155, datetime=Timestamp('2008-10-23 10:34:29'), timestamp=1224758069.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979017, longitude=116.327211, altitude=154, datetime=Timestamp('2008-10-23 10:34:34'), timestamp=1224758074.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979013, longitude=116.327154, altitude=150, datetime=Timestamp('2008-10-23 10:34:39'), timestamp=1224758079.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979088, longitude=116.327131, altitude=148, datetime=Timestamp('2008-10-23 10:34:44'), timestamp=1224758084.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979104, longitude=116.327143, altitude=143, datetime=Timestamp('2008-10-23 10:34:49'), timestamp=1224758089.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979195, longitude=116.327168, altitude=137, datetime=Timestamp('2008-10-23 10:34:52'), timestamp=1224758092.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979293, longitude=116.327209, altitude=134, datetime=Timestamp('2008-10-23 10:34:55'), timestamp=1224758095.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979394, longitude=116.327208, altitude=132, datetime=Timestamp('2008-10-23 10:34:58'), timestamp=1224758098.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979497, longitude=116.327198, altitude=131, datetime=Timestamp('2008-10-23 10:35:00'), timestamp=1224758100.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979629, longitude=116.327197, altitude=131, datetime=Timestamp('2008-10-23 10:35:02'), timestamp=1224758102.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979719, longitude=116.327182, altitude=128, datetime=Timestamp('2008-10-23 10:35:05'), timestamp=1224758105.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979831, longitude=116.327185, altitude=132, datetime=Timestamp('2008-10-23 10:35:07'), timestamp=1224758107.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979919, longitude=116.327151, altitude=124, datetime=Timestamp('2008-10-23 10:35:12'), timestamp=1224758112.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.979973, longitude=116.327109, altitude=109, datetime=Timestamp('2008-10-23 10:35:17'), timestamp=1224758117.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980092, longitude=116.327084, altitude=96, datetime=Timestamp('2008-10-23 10:35:21'), timestamp=1224758121.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980126, longitude=116.327037, altitude=83, datetime=Timestamp('2008-10-23 10:35:26'), timestamp=1224758126.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980188, longitude=116.326994, altitude=69, datetime=Timestamp('2008-10-23 10:35:31'), timestamp=1224758131.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98028, longitude=116.326988, altitude=66, datetime=Timestamp('2008-10-23 10:35:36'), timestamp=1224758136.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980404, longitude=116.326978, altitude=63, datetime=Timestamp('2008-10-23 10:35:39'), timestamp=1224758139.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980522, longitude=116.326976, altitude=58, datetime=Timestamp('2008-10-23 10:35:43'), timestamp=1224758143.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980658, longitude=116.326933, altitude=49, datetime=Timestamp('2008-10-23 10:35:45'), timestamp=1224758145.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980765, longitude=116.326905, altitude=45, datetime=Timestamp('2008-10-23 10:35:48'), timestamp=1224758148.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98087, longitude=116.326873, altitude=40, datetime=Timestamp('2008-10-23 10:35:51'), timestamp=1224758151.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.980956, longitude=116.32682, altitude=34, datetime=Timestamp('2008-10-23 10:35:55'), timestamp=1224758155.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981364, longitude=116.326798, altitude=16, datetime=Timestamp('2008-10-23 10:36:01'), timestamp=1224758161.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981473, longitude=116.326765, altitude=11, datetime=Timestamp('2008-10-23 10:36:03'), timestamp=1224758163.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981748, longitude=116.326759, altitude=19, datetime=Timestamp('2008-10-23 10:36:06'), timestamp=1224758166.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.981959, longitude=116.326767, altitude=26, datetime=Timestamp('2008-10-23 10:36:07'), timestamp=1224758167.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982049, longitude=116.326757, altitude=26, datetime=Timestamp('2008-10-23 10:36:08'), timestamp=1224758168.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982175, longitude=116.326752, altitude=29, datetime=Timestamp('2008-10-23 10:36:09'), timestamp=1224758169.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98228, longitude=116.326754, altitude=31, datetime=Timestamp('2008-10-23 10:36:10'), timestamp=1224758170.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982387, longitude=116.326752, altitude=31, datetime=Timestamp('2008-10-23 10:36:12'), timestamp=1224758172.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982508, longitude=116.326766, altitude=31, datetime=Timestamp('2008-10-23 10:36:15'), timestamp=1224758175.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982601, longitude=116.32673, altitude=29, datetime=Timestamp('2008-10-23 10:36:20'), timestamp=1224758180.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982675, longitude=116.326684, altitude=22, datetime=Timestamp('2008-10-23 10:36:25'), timestamp=1224758185.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982808, longitude=116.32671, altitude=16, datetime=Timestamp('2008-10-23 10:36:29'), timestamp=1224758189.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.982922, longitude=116.326697, altitude=13, datetime=Timestamp('2008-10-23 10:36:32'), timestamp=1224758192.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983115, longitude=116.326693, altitude=8, datetime=Timestamp('2008-10-23 10:36:35'), timestamp=1224758195.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983215, longitude=116.326708, altitude=10, datetime=Timestamp('2008-10-23 10:36:38'), timestamp=1224758198.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98336, longitude=116.326707, altitude=17, datetime=Timestamp('2008-10-23 10:36:42'), timestamp=1224758202.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983434, longitude=116.326665, altitude=3, datetime=Timestamp('2008-10-23 10:36:47'), timestamp=1224758207.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983559, longitude=116.326665, altitude=0, datetime=Timestamp('2008-10-23 10:36:50'), timestamp=1224758210.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983719, longitude=116.326661, altitude=-1, datetime=Timestamp('2008-10-23 10:36:52'), timestamp=1224758212.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983839, longitude=116.326694, altitude=11, datetime=Timestamp('2008-10-23 10:36:54'), timestamp=1224758214.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.983933, longitude=116.326715, altitude=18, datetime=Timestamp('2008-10-23 10:36:56'), timestamp=1224758216.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984062, longitude=116.326728, altitude=29, datetime=Timestamp('2008-10-23 10:37:00'), timestamp=1224758220.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984142, longitude=116.326753, altitude=35, datetime=Timestamp('2008-10-23 10:37:05'), timestamp=1224758225.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984164, longitude=116.326724, altitude=31, datetime=Timestamp('2008-10-23 10:37:10'), timestamp=1224758230.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984262, longitude=116.326723, altitude=28, datetime=Timestamp('2008-10-23 10:37:15'), timestamp=1224758235.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984354, longitude=116.326715, altitude=27, datetime=Timestamp('2008-10-23 10:37:18'), timestamp=1224758238.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984457, longitude=116.326711, altitude=29, datetime=Timestamp('2008-10-23 10:37:21'), timestamp=1224758241.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984559, longitude=116.326696, altitude=27, datetime=Timestamp('2008-10-23 10:37:26'), timestamp=1224758246.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984669, longitude=116.326711, altitude=29, datetime=Timestamp('2008-10-23 10:37:30'), timestamp=1224758250.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984783, longitude=116.326683, altitude=25, datetime=Timestamp('2008-10-23 10:37:35'), timestamp=1224758255.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.984889, longitude=116.326672, altitude=18, datetime=Timestamp('2008-10-23 10:37:39'), timestamp=1224758259.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985019, longitude=116.326677, altitude=20, datetime=Timestamp('2008-10-23 10:37:42'), timestamp=1224758262.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985106, longitude=116.326694, altitude=28, datetime=Timestamp('2008-10-23 10:37:43'), timestamp=1224758263.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985197, longitude=116.326686, altitude=31, datetime=Timestamp('2008-10-23 10:37:45'), timestamp=1224758265.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985304, longitude=116.326664, altitude=29, datetime=Timestamp('2008-10-23 10:37:48'), timestamp=1224758268.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985454, longitude=116.32661, altitude=31, datetime=Timestamp('2008-10-23 10:37:52'), timestamp=1224758272.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985546, longitude=116.326565, altitude=28, datetime=Timestamp('2008-10-23 10:37:57'), timestamp=1224758277.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985645, longitude=116.326589, altitude=29, datetime=Timestamp('2008-10-23 10:38:00'), timestamp=1224758280.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985752, longitude=116.326618, altitude=28, datetime=Timestamp('2008-10-23 10:38:03'), timestamp=1224758283.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.98585, longitude=116.326633, altitude=33, datetime=Timestamp('2008-10-23 10:38:06'), timestamp=1224758286.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.985948, longitude=116.326605, altitude=36, datetime=Timestamp('2008-10-23 10:38:10'), timestamp=1224758290.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.986049, longitude=116.326554, altitude=38, datetime=Timestamp('2008-10-23 10:38:14'), timestamp=1224758294.0, label=None, time_diff=None, distance=None, speed=None), Record(user_id='001', trajectory_id='001_0', latitude=39.986141, longitud

In [190]:

import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

data_path, project_path, output_path = os.getenv('DATA_PATH'), os.getenv('PROJECT_PATH'), os.getenv('OUTPUT_PATH')
os.chdir(os.path.join(project_path, 'src'))

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline


t: Trajectories = pickle.load(open(os.path.join(output_path, 'trajectories_001.pkl'), 'rb'))
len(t.trajectories)

71

In [191]:
t = Trajectories([t.trajectories[0]])

In [187]:
t.gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
0,001,001_0,39.984094,116.319236,492,2008-10-23 05:53:05,1.224741e+09,None,0.0,0.000000,0.000000
1,001,001_0,39.984198,116.319322,492,2008-10-23 05:53:06,1.224741e+09,None,1.0,13.685897,13.685897
2,001,001_0,39.984224,116.319402,492,2008-10-23 05:53:11,1.224741e+09,None,5.0,7.417894,1.483579
3,001,001_0,39.984211,116.319389,492,2008-10-23 05:53:16,1.224741e+09,None,5.0,1.821118,0.364224
4,001,001_0,39.984217,116.319422,491,2008-10-23 05:53:21,1.224741e+09,None,5.0,2.896307,0.579261
...,...,...,...,...,...,...,...,...,...,...,...
956,001,001_0,40.013804,116.306532,90,2008-10-23 12:04:13,1.224763e+09,None,5.0,0.000000,0.000000
957,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:18,1.224763e+09,None,5.0,0.111035,0.022207
958,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:23,1.224763e+09,None,5.0,0.000000,0.000000
959,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:26,1.224763e+09,None,3.0,0.000000,0.000000
960,001,001_0,40.013803,116.306531,90,2008-10-23 12:04:28,1.224763e+09,None,2.0,0.085377,0.042688

In [194]:
t.filter_trajectories(datetime_range).gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
148,001,001_0,39.970511,116.341455,492,2008-10-23 10:32:53,1.224758e+09,None,16256.0,1454.039870,0.089446
149,001,001_0,39.977648,116.326925,277,2008-10-23 10:33:00,1.224758e+09,None,7.0,1472.636782,210.376683
150,001,001_0,39.977586,116.326918,296,2008-10-23 10:33:05,1.224758e+09,None,5.0,6.910041,1.382008
151,001,001_0,39.977596,116.326894,299,2008-10-23 10:33:10,1.224758e+09,None,5.0,2.331493,0.466299
152,001,001_0,39.977661,116.326947,280,2008-10-23 10:33:14,1.224758e+09,None,4.0,8.519696,2.129924
...,...,...,...,...,...,...,...,...,...,...,...
347,001,001_0,39.995749,116.326488,176,2008-10-23 10:44:53,1.224759e+09,None,1.0,13.693072,13.693072
348,001,001_0,39.995853,116.326562,161,2008-10-23 10:44:55,1.224759e+09,None,2.0,13.163715,6.581858
349,001,001_0,39.995894,116.326665,145,2008-10-23 10:44:59,1.224759e+09,None,4.0,9.904333,2.476083
350,001,001_0,39.995959,116.326688,139,2008-10-23 10:45:04,1.224759e+09,None,5.0,7.479748,1.495950
351,001,001_0,39.996067,116.326669,134,2008-10-23 10:45:09,1.224759e+09,None,5.0,12.101008,2.420202

In [189]:
t.gdf

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
0,001,001_0,39.984094,116.319236,492,2008-10-23 05:53:05,1.224741e+09,None,0.0,0.000000,0.000000
1,001,001_0,39.984198,116.319322,492,2008-10-23 05:53:06,1.224741e+09,None,1.0,13.685897,13.685897
2,001,001_0,39.984224,116.319402,492,2008-10-23 05:53:11,1.224741e+09,None,5.0,7.417894,1.483579
3,001,001_0,39.984211,116.319389,492,2008-10-23 05:53:16,1.224741e+09,None,5.0,1.821118,0.364224
4,001,001_0,39.984217,116.319422,491,2008-10-23 05:53:21,1.224741e+09,None,5.0,2.896307,0.579261
...,...,...,...,...,...,...,...,...,...,...,...
956,001,001_0,40.013804,116.306532,90,2008-10-23 12:04:13,1.224763e+09,None,5.0,0.000000,0.000000
957,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:18,1.224763e+09,None,5.0,0.111035,0.022207
958,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:23,1.224763e+09,None,5.0,0.000000,0.000000
959,001,001_0,40.013803,116.306532,90,2008-10-23 12:04:26,1.224763e+09,None,3.0,0.000000,0.000000
960,001,001_0,40.013803,116.306531,90,2008-10-23 12:04:28,1.224763e+09,None,2.0,0.085377,0.042688