In [2]:
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
import importlib

import pandas as pd
import pickle

import models.trajectory
importlib.reload(models.trajectory)
from models.trajectory import Trajectory

import models.trajectories
importlib.reload(models.trajectories)
from models.trajectories import Trajectories

import utils.trackmap
importlib.reload(utils.trackmap)
from utils.trackmap import plot_map

import utils.timeline
importlib.reload(utils.timeline)
from utils.timeline import plot_timeline

In [4]:
trajectories = Trajectories.from_user(user_id='001', data_path='../data/geolife/')

Loaded trajectory 001_0 with 961 records
Loaded trajectory 001_1 with 2128 records
Loaded trajectory 001_2 with 7075 records
Loaded trajectory 001_3 with 3676 records
Loaded trajectory 001_4 with 3236 records
Loaded trajectory 001_5 with 827 records
Loaded trajectory 001_6 with 498 records
Loaded trajectory 001_7 with 99 records
Loaded trajectory 001_8 with 647 records
Loaded trajectory 001_9 with 336 records
Loaded trajectory 001_10 with 252 records
Loaded trajectory 001_11 with 732 records
Loaded trajectory 001_12 with 1988 records
Loaded trajectory 001_13 with 1482 records
Loaded trajectory 001_14 with 3712 records
Loaded trajectory 001_15 with 1943 records
Loaded trajectory 001_16 with 537 records
Loaded trajectory 001_17 with 478 records
Loaded trajectory 001_18 with 649 records
Loaded trajectory 001_19 with 1889 records
Loaded trajectory 001_20 with 747 records
Loaded trajectory 001_21 with 5718 records
Loaded trajectory 001_22 with 254 records
Loaded trajectory 001_23 with 543 records
Loaded trajectory 001_24 with 2900 records
Loaded trajectory 001_25 with 3812 records
Loaded trajectory 001_26 with 2472 records
Loaded trajectory 001_27 with 789 records
Loaded trajectory 001_28 with 323 records
Loaded trajectory 001_29 with 1612 records
Loaded trajectory 001_30 with 832 records
Loaded trajectory 001_31 with 495 records
Loaded trajectory 001_32 with 656 records
Loaded trajectory 001_33 with 981 records
Loaded trajectory 001_34 with 5663 records
Loaded trajectory 001_35 with 2789 records
Loaded trajectory 001_36 with 1000 records
Loaded trajectory 001_37 with 3028 records
Loaded trajectory 001_38 with 694 records
Loaded trajectory 001_39 with 145 records
Loaded trajectory 001_40 with 821 records
Loaded trajectory 001_41 with 859 records
Loaded trajectory 001_42 with 1779 records
Loaded trajectory 001_43 with 697 records
Loaded trajectory 001_44 with 863 records
Loaded trajectory 001_45 with 721 records
Loaded trajectory 001_46 with 491 records
Loaded trajectory 001_47 with 482 records
Loaded trajectory 001_48 with 516 records
Loaded trajectory 001_49 with 538 records
Loaded trajectory 001_50 with 934 records
Loaded trajectory 001_51 with 566 records
Loaded trajectory 001_52 with 859 records
Loaded trajectory 001_53 with 495 records
Loaded trajectory 001_54 with 2868 records
Loaded trajectory 001_55 with 59 records
Loaded trajectory 001_56 with 33 records
Loaded trajectory 001_57 with 117 records
Loaded trajectory 001_58 with 2564 records
Loaded trajectory 001_59 with 534 records
Loaded trajectory 001_60 with 603 records
Loaded trajectory 001_61 with 6959 records
Loaded trajectory 001_62 with 835 records
Loaded trajectory 001_63 with 1456 records
Loaded trajectory 001_64 with 888 records
Loaded trajectory 001_65 with 919 records
Loaded trajectory 001_66 with 1842 records
Loaded trajectory 001_67 with 691 records
Loaded trajectory 001_68 with 7584 records
Loaded trajectory 001_69 with 897 records
Loaded trajectory 001_70 with 539 records

In [5]:
trajectories.compute_trajectories_speed()
trajectories.gdf.head()

Computing speed for trajectory 001_0 with 961 records
Computing speed for trajectory 001_1 with 2128 records
Computing speed for trajectory 001_2 with 7075 records
Computing speed for trajectory 001_3 with 3676 records
Computing speed for trajectory 001_4 with 3236 records
Computing speed for trajectory 001_5 with 827 records
Computing speed for trajectory 001_6 with 498 records
Computing speed for trajectory 001_7 with 99 records
Computing speed for trajectory 001_8 with 647 records
Computing speed for trajectory 001_9 with 336 records
Computing speed for trajectory 001_10 with 252 records
Computing speed for trajectory 001_11 with 732 records
Computing speed for trajectory 001_12 with 1988 records
Computing speed for trajectory 001_13 with 1482 records
Computing speed for trajectory 001_14 with 3712 records
Computing speed for trajectory 001_15 with 1943 records
Computing speed for trajectory 001_16 with 537 records
Computing speed for trajectory 001_17 with 478 records
Computing speed for trajectory 001_18 with 649 records
Computing speed for trajectory 001_19 with 1889 records
Computing speed for trajectory 001_20 with 747 records
Computing speed for trajectory 001_21 with 5718 records
Computing speed for trajectory 001_22 with 254 records
Computing speed for trajectory 001_23 with 543 records
Computing speed for trajectory 001_24 with 2900 records
Computing speed for trajectory 001_25 with 3812 records
Computing speed for trajectory 001_26 with 2472 records
Computing speed for trajectory 001_27 with 789 records
Computing speed for trajectory 001_28 with 323 records
Computing speed for trajectory 001_29 with 1612 records
Computing speed for trajectory 001_30 with 832 records
Computing speed for trajectory 001_31 with 495 records
Computing speed for trajectory 001_32 with 656 records
Computing speed for trajectory 001_33 with 981 records
Computing speed for trajectory 001_34 with 5663 records
Computing speed for trajectory 001_35 with 2789 records
Computing speed for trajectory 001_36 with 1000 records
Computing speed for trajectory 001_37 with 3028 records
Computing speed for trajectory 001_38 with 694 records
Computing speed for trajectory 001_39 with 145 records
Computing speed for trajectory 001_40 with 821 records
Computing speed for trajectory 001_41 with 859 records
Computing speed for trajectory 001_42 with 1779 records
Computing speed for trajectory 001_43 with 697 records
Computing speed for trajectory 001_44 with 863 records
Computing speed for trajectory 001_45 with 721 records
Computing speed for trajectory 001_46 with 491 records
Computing speed for trajectory 001_47 with 482 records
Computing speed for trajectory 001_48 with 516 records
Computing speed for trajectory 001_49 with 538 records
Computing speed for trajectory 001_50 with 934 records
Computing speed for trajectory 001_51 with 566 records
Computing speed for trajectory 001_52 with 859 records
Computing speed for trajectory 001_53 with 495 records
Computing speed for trajectory 001_54 with 2868 records
Computing speed for trajectory 001_55 with 59 records
Computing speed for trajectory 001_56 with 33 records
Computing speed for trajectory 001_57 with 117 records
Computing speed for trajectory 001_58 with 2564 records
Computing speed for trajectory 001_59 with 534 records
Computing speed for trajectory 001_60 with 603 records
Computing speed for trajectory 001_61 with 6959 records
Computing speed for trajectory 001_62 with 835 records
Computing speed for trajectory 001_63 with 1456 records
Computing speed for trajectory 001_64 with 888 records
Computing speed for trajectory 001_65 with 919 records
Computing speed for trajectory 001_66 with 1842 records
Computing speed for trajectory 001_67 with 691 records
Computing speed for trajectory 001_68 with 7584 records
Computing speed for trajectory 001_69 with 897 records
Computing speed for trajectory 001_70 with 539 records

,user_id,trajectory_id,latitude,longitude,altitude,datetime,timestamp,label,time_diff,distance,speed
0,001,001_0,39.984094,116.319236,492,2008-10-23 05:53:05,1.224741e+09,None,0.0,0.000000,0.000000
1,001,001_0,39.984198,116.319322,492,2008-10-23 05:53:06,1.224741e+09,None,1.0,13.685897,13.685897
2,001,001_0,39.984224,116.319402,492,2008-10-23 05:53:11,1.224741e+09,None,5.0,7.417894,1.483579
3,001,001_0,39.984211,116.319389,492,2008-10-23 05:53:16,1.224741e+09,None,5.0,1.821118,0.364224
4,001,001_0,39.984217,116.319422,491,2008-10-23 05:53:21,1.224741e+09,None,5.0,2.896307,0.579261

In [6]:
with open('data/trajectories_001.pkl', 'wb') as f:
    pickle.dump(trajectories, f)